"use client";

import { useMemo, useState } from "react";
import { Activity, AlertTriangle, ArrowDownRight, ArrowUpRight, BarChart3, Bot, Check, ChevronDown, Clock3, Gauge, Pause, Play, RefreshCw, ShieldCheck, Target, TrendingUp, Zap } from "lucide-react";

type BotState = "running" | "paused";
type Strategy = { id: string; name: string; short: string; description: string; color: string; state: BotState; score: number; trades: number; return: string; drawdown: string; accent: string };

const initialStrategies: Strategy[] = [
  { id: "orb", name: "Opening Range Breakout", short: "ORB", description: "Breaks above or below the first 30-minute range.", color: "#2e90fa", state: "running", score: 82, trades: 18, return: "+8.4%", drawdown: "−2.1%", accent: "bg-[#eff8ff] text-[#175cd3] border-[#b2ddff]" },
  { id: "news", name: "Insider + News", short: "NEWS", description: "Filters headlines and insider filings for catalyst trades.", color: "#9e77ed", state: "running", score: 74, trades: 9, return: "+5.8%", drawdown: "−3.4%", accent: "bg-[#f9f5ff] text-[#6941c6] border-[#e9d7fe]" },
  { id: "lvl", name: "Liquidity Levels", short: "LVL", description: "Mean reversion after a liquidity sweep at key levels.", color: "#f79009", state: "paused", score: 68, trades: 13, return: "+3.1%", drawdown: "−1.8%", accent: "bg-[#fffaeb] text-[#b54708] border-[#fedf89]" },
];

const activity = [
  ["10:32:14", "ORB", "AAPL", "Long candidate screened", "82%", "#12b76a"],
  ["10:28:51", "NEWS", "NVDA", "Skipped · low confidence", "44%", "#98a2b3"],
  ["09:47:06", "ORB", "MSFT", "Position closed · target hit", "+$86.20", "#12b76a"],
  ["09:31:22", "LVL", "TSLA", "Risk gate rejected", "−0.8R", "#f04438"],
  ["09:30:04", "ORB", "AMD", "Opening range captured", "Ready", "#2e90fa"],
];

export function TradingDashboard({ paperMode, activeNav }: { paperMode: boolean; activeNav: string }) {
  const [strategies, setStrategies] = useState(initialStrategies);
  const [runningBacktest, setRunningBacktest] = useState(false);
  const [days, setDays] = useState("90 days");
  const [showAll, setShowAll] = useState(false);
  const [risk, setRisk] = useState(1);
  const [paused, setPaused] = useState(false);
  const visibleActivity = showAll ? activity : activity.slice(0, 4);
  const activeCount = useMemo(() => strategies.filter((s) => s.state === "running").length, [strategies]);

  function toggleStrategy(id: string) { setStrategies((current) => current.map((s) => s.id === id ? { ...s, state: s.state === "running" ? "paused" : "running" } : s)); }
  function runBacktest() { setRunningBacktest(true); window.setTimeout(() => setRunningBacktest(false), 1200); }

  if (activeNav !== "Overview") return <ComingSoon name={activeNav} />;
  return <div className="space-y-6">
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">
      <Metric label="Paper equity" value="$25,842.60" change="+$842.60" note="since start" positive icon={<WalletIcon />} />
      <Metric label="Total return" value="+3.37%" change="+1.12%" note="vs. benchmark" positive icon={<TrendingUp size={17} />} />
      <Metric label="Win rate" value="61.5%" change="+4.2%" note="last 40 trades" positive icon={<Target size={17} />} />
      <Metric label="Max drawdown" value="−2.8%" change="within limit" note="guardrail: −5%" icon={<ShieldCheck size={17} />} />
    </div>

    <div className="grid gap-6 xl:grid-cols-[minmax(0,1.6fr)_minmax(340px,1fr)]">
      <section className="rounded-xl border border-[#e4e7ec] bg-white p-5 shadow-[0_1px_2px_rgba(16,24,40,0.03)] sm:p-6">
        <div className="mb-5 flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><h2 className="text-base font-semibold">Equity curve</h2><span className="rounded-full bg-[#ecfdf3] px-2 py-0.5 text-[10px] font-semibold text-[#027a48]">PAPER</span></div><p className="mt-1 text-xs text-[#667085]">Cumulative performance across enabled strategies</p></div><select value={days} onChange={(e) => setDays(e.target.value)} className="rounded-lg border border-[#d0d5dd] bg-white px-2.5 py-1.5 text-xs font-medium text-[#344054] outline-none"><option>30 days</option><option>90 days</option><option>1 year</option></select></div>
        <div className="relative h-56 overflow-hidden rounded-lg bg-[#fbfcfe] px-2 pt-3"><div className="absolute inset-0 flex flex-col justify-between px-2 py-3"><span className="border-t border-dashed border-[#eaecf0] text-[10px] text-[#98a2b3]">$26k</span><span className="border-t border-dashed border-[#eaecf0] text-[10px] text-[#98a2b3]">$25k</span><span className="border-t border-dashed border-[#eaecf0] text-[10px] text-[#98a2b3]">$24k</span><span className="border-t border-dashed border-[#eaecf0] text-[10px] text-[#98a2b3]">$23k</span></div><svg viewBox="0 0 780 205" preserveAspectRatio="none" className="absolute inset-x-4 bottom-7 top-3 h-[calc(100%-2.5rem)] w-[calc(100%-2rem)]"><defs><linearGradient id="area" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#12b76a" stopOpacity=".22"/><stop offset="1" stopColor="#12b76a" stopOpacity="0"/></linearGradient></defs><path d="M0,169 C42,165 56,148 87,153 S131,142 157,148 S193,126 221,132 S250,118 278,123 S311,110 342,119 S371,98 400,105 S431,87 456,94 S492,71 518,79 S549,58 580,65 S618,52 646,57 S682,35 705,42 S742,21 780,26 V205 H0Z" fill="url(#area)"/><path d="M0,169 C42,165 56,148 87,153 S131,142 157,148 S193,126 221,132 S250,118 278,123 S311,110 342,119 S371,98 400,105 S431,87 456,94 S492,71 518,79 S549,58 580,65 S618,52 646,57 S682,35 705,42 S742,21 780,26" fill="none" stroke="#12b76a" strokeLinecap="round" strokeWidth="3"/></svg><div className="absolute bottom-2 left-3 right-3 flex justify-between text-[10px] text-[#98a2b3]"><span>Jul 03</span><span>Jul 17</span><span>Aug 01</span><span>Aug 15</span><span>Aug 29</span></div></div><div className="mt-4 flex flex-wrap gap-x-5 gap-y-2 text-[11px] text-[#667085]"><span className="flex items-center gap-1.5"><i className="h-2 w-2 rounded-full bg-[#12b76a]" />Combined equity</span><span className="flex items-center gap-1.5"><i className="h-2 w-2 rounded-full bg-[#d0d5dd]" />Starting balance $25,000</span><span className="ml-auto font-medium text-[#027a48]">+3.37% net</span></div>
      </section>
      <section className="rounded-xl border border-[#e4e7ec] bg-white p-5 shadow-[0_1px_2px_rgba(16,24,40,0.03)] sm:p-6"><div className="mb-5 flex items-start justify-between"><div><h2 className="text-base font-semibold">System health</h2><p className="mt-1 text-xs text-[#667085]">Decision funnel status</p></div><span className="flex items-center gap-1.5 text-xs font-medium text-[#027a48]"><span className="h-2 w-2 animate-pulse rounded-full bg-[#12b76a]" />Live</span></div><div className="space-y-4"><Health label="Market data" detail="Alpaca · 24ms" status="Connected" /><Health label="AI confidence layer" detail="Jev decision engine" status="Ready" /><Health label="Risk gate" detail={`Max daily loss · ${risk}%`} status="Armed" /><Health label="Broker" detail="Paper account" status={paperMode ? "Simulation" : "Locked"} /></div><div className="mt-5 rounded-lg border border-[#fedf89] bg-[#fffaeb] p-3 text-xs text-[#93370d]"><div className="flex gap-2"><AlertTriangle size={15} className="mt-0.5 shrink-0" /><p><strong>Safety first:</strong> paper mode is active. Live order routing is not configured.</p></div></div></section>
    </div>

    <section className="rounded-xl border border-[#e4e7ec] bg-white p-5 shadow-[0_1px_2px_rgba(16,24,40,0.03)] sm:p-6"><div className="mb-5 flex flex-wrap items-end justify-between gap-3"><div><div className="flex items-center gap-2"><h2 className="text-base font-semibold">Strategy bots</h2><span className="rounded-full bg-[#f2f4f7] px-2 py-0.5 text-[10px] font-semibold text-[#475467]">{activeCount}/3 ACTIVE</span></div><p className="mt-1 text-xs text-[#667085]">Each signal passes through rules → confidence → risk gate before execution.</p></div><button className="flex items-center gap-2 rounded-lg border border-[#d0d5dd] bg-white px-3 py-2 text-xs font-semibold text-[#344054] hover:bg-[#f9fafb]" onClick={() => setPaused(!paused)}>{paused ? <Play size={14} /> : <Pause size={14} />}{paused ? "Resume all" : "Pause all"}</button></div><div className="grid gap-3 lg:grid-cols-3">{strategies.map((strategy) => <StrategyCard key={strategy.id} strategy={{ ...strategy, state: paused ? "paused" : strategy.state }} onToggle={() => toggleStrategy(strategy.id)} />)}</div></section>

    <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_340px]"><section className="rounded-xl border border-[#e4e7ec] bg-white p-5 shadow-[0_1px_2px_rgba(16,24,40,0.03)] sm:p-6"><div className="mb-4 flex items-center justify-between"><div><h2 className="text-base font-semibold">Recent activity</h2><p className="mt-1 text-xs text-[#667085]">Latest decisions from the paper execution loop</p></div><button className="text-xs font-medium text-[#175cd3] hover:underline" onClick={() => setShowAll(!showAll)}>{showAll ? "Show less" : "View all"}</button></div><div className="overflow-x-auto"><table className="w-full min-w-[580px] text-left text-xs"><thead className="border-b border-[#eaecf0] text-[10px] uppercase tracking-[0.1em] text-[#98a2b3]"><tr><th className="pb-3 font-medium">Time</th><th className="pb-3 font-medium">Bot</th><th className="pb-3 font-medium">Symbol</th><th className="pb-3 font-medium">Decision</th><th className="pb-3 text-right font-medium">Result</th></tr></thead><tbody>{visibleActivity.map(([time, bot, symbol, decision, result, color]) => <tr key={`${time}-${symbol}`} className="border-b border-[#f2f4f7] last:border-0"><td className="py-3 font-mono text-[#667085]">{time}</td><td className="py-3"><span className="rounded bg-[#f2f4f7] px-1.5 py-1 text-[10px] font-bold text-[#475467]">{bot}</span></td><td className="py-3 font-semibold">{symbol}</td><td className="py-3 text-[#475467]">{decision}</td><td className="py-3 text-right font-semibold" style={{ color }}>{result}</td></tr>)}</tbody></table></div></section><section className="rounded-xl border border-[#e4e7ec] bg-white p-5 shadow-[0_1px_2px_rgba(16,24,40,0.03)] sm:p-6"><div className="mb-4 flex items-center gap-2"><Gauge size={17} className="text-[#f79009]" /><h2 className="text-base font-semibold">Risk controls</h2></div><div className="space-y-4"><div className="flex items-center justify-between text-xs"><span className="text-[#667085]">Risk per trade</span><strong>{risk.toFixed(1)}%</strong></div><input aria-label="Risk per trade" type="range" min="0.5" max="2" step="0.1" value={risk} onChange={(e) => setRisk(Number(e.target.value))} className="w-full accent-[#12b76a]" /><div className="grid grid-cols-2 gap-2"><RiskStat label="Daily loss limit" value="−5.0%" /><RiskStat label="Max positions" value="3" /><RiskStat label="Kill switch" value="Armed" green /><RiskStat label="Sizing" value="Fixed risk" /></div><button onClick={runBacktest} disabled={runningBacktest} className="mt-2 flex w-full items-center justify-center gap-2 rounded-lg bg-[#111827] px-3 py-2.5 text-xs font-semibold text-white transition hover:bg-[#1d2939] disabled:opacity-70">{runningBacktest ? <RefreshCw size={14} className="animate-spin" /> : <Play size={14} fill="currentColor" />}{runningBacktest ? "Running 90-day backtest…" : "Run paper backtest"}</button><p className="text-center text-[10px] text-[#98a2b3]">Uses historical data · no orders sent</p></div></section></div>
    <p className="flex items-center justify-center gap-1.5 pb-2 text-center text-[11px] text-[#98a2b3]"><ShieldCheck size={13} /> Built for experimentation. This is not financial advice. Start with paper trading.</p>
  </div>;
}

function Metric({ label, value, change, note, positive, icon }: { label: string; value: string; change: string; note: string; positive?: boolean; icon: React.ReactNode }) { return <div className="rounded-xl border border-[#e4e7ec] bg-white p-4 shadow-[0_1px_2px_rgba(16,24,40,0.03)] sm:p-5"><div className="mb-3 flex items-center justify-between"><span className="text-xs text-[#667085]">{label}</span><span className="text-[#98a2b3]">{icon}</span></div><p className="text-xl font-semibold tracking-tight sm:text-2xl">{value}</p><p className={`mt-1 text-[11px] font-medium ${positive ? "text-[#027a48]" : "text-[#667085]"}`}>{positive && <ArrowUpRight size={12} className="mr-0.5 inline" />}{change} <span className="font-normal text-[#98a2b3]">{note}</span></p></div>; }
function StrategyCard({ strategy, onToggle }: { strategy: Strategy; onToggle: () => void }) { const live = strategy.state === "running"; return <div className="rounded-xl border border-[#eaecf0] p-4 transition hover:border-[#d0d5dd] hover:shadow-sm"><div className="mb-4 flex items-start justify-between"><div className={`flex h-9 w-9 items-center justify-center rounded-lg border text-[10px] font-bold ${strategy.accent}`}>{strategy.short}</div><button onClick={onToggle} className={`relative h-5 w-9 rounded-full transition ${live ? "bg-[#12b76a]" : "bg-[#d0d5dd]"}`} aria-label={`${live ? "Pause" : "Start"} ${strategy.name}`}><span className={`absolute top-0.5 h-4 w-4 rounded-full bg-white shadow transition ${live ? "left-[18px]" : "left-0.5"}`} /></button></div><h3 className="text-sm font-semibold">{strategy.name}</h3><p className="mt-1 min-h-8 text-xs leading-5 text-[#667085]">{strategy.description}</p><div className="my-4 grid grid-cols-3 gap-2 border-y border-[#f2f4f7] py-3"><div><p className="text-[10px] text-[#98a2b3]">AI score</p><p className="mt-1 text-sm font-semibold">{strategy.score}%</p></div><div><p className="text-[10px] text-[#98a2b3]">Trades</p><p className="mt-1 text-sm font-semibold">{strategy.trades}</p></div><div><p className="text-[10px] text-[#98a2b3]">Return</p><p className="mt-1 text-sm font-semibold text-[#027a48]">{strategy.return}</p></div></div><div className="flex items-center justify-between text-[11px]"><span className={`flex items-center gap-1.5 font-medium ${live ? "text-[#027a48]" : "text-[#98a2b3]"}`}><span className={`h-1.5 w-1.5 rounded-full ${live ? "bg-[#12b76a]" : "bg-[#98a2b3]"}`} />{live ? "Monitoring market" : "Paused"}</span><span className="text-[#667085]">DD {strategy.drawdown}</span></div></div>; }
function Health({ label, detail, status }: { label: string; detail: string; status: string }) { return <div className="flex items-center gap-3"><div className="flex h-8 w-8 items-center justify-center rounded-lg bg-[#f2f4f7] text-[#667085]"><Check size={15} /></div><div className="min-w-0 flex-1"><p className="text-xs font-medium">{label}</p><p className="mt-0.5 truncate text-[10px] text-[#98a2b3]">{detail}</p></div><span className="text-[10px] font-medium text-[#027a48]">{status}</span></div>; }
function RiskStat({ label, value, green }: { label: string; value: string; green?: boolean }) { return <div className="rounded-lg bg-[#f9fafb] p-2.5"><p className="text-[10px] text-[#98a2b3]">{label}</p><p className={`mt-1 text-xs font-semibold ${green ? "text-[#027a48]" : "text-[#344054]"}`}>{value}</p></div>; }
function ComingSoon({ name }: { name: string }) { return <div className="flex min-h-[480px] flex-col items-center justify-center rounded-xl border border-dashed border-[#d0d5dd] bg-white text-center"><div className="mb-4 flex h-12 w-12 items-center justify-center rounded-xl bg-[#ecfdf3] text-[#027a48]"><Bot size={22} /></div><h2 className="text-lg font-semibold">{name} workspace</h2><p className="mt-2 max-w-sm text-sm text-[#667085]">This section is scaffolded for the next build step. The overview is ready for safe paper-trading experiments.</p></div>; }
function WalletIcon() { return <span className="text-[15px]">$</span>; }
